### ISSUE TITLE
Default value of direction should be up

### ISSUE THREAD

**Issue by sebastianjung** [jsnanigans/vue-parallax-js#10]
hey there,

thanks for that awesome package. Just wanted to say, that the default direction states 'down' in the readme of this repo but it should be 'up' i guess.

Best regards,

Sebastian

**Comment by sebastianjung** [comment]
Nevermind, was looking at the wrong documentation :D

**Comment by jsnanigans** [comment]
Hey Sebastian, I'm glad you like it.
Let me know if you have any issues
