### ISSUE TITLE
any way to reposition element

### ISSUE THREAD

**Issue by sebastianjung** [jsnanigans/vue-parallax-js#11]
Hey there,

is there any way to reposition the element because after i applied v-parallax to it it has a different position. It is slightly lower positioned than withough the directive on it.

I could archive this of course by using css but it is a hassle to do this on every element i want to have the parallax effect on.

Any help would be appreciated :)

Greetings and thanks in advance,

Sebastian Jung

**Comment by jsnanigans** [comment]
Hey, you can try to use `<h1 v-parallax.absY="0.2">vue-parallax-js</h1>`
that solved some of those problems for me, but if that does not work i'm not sure what you could do

**Comment by sebastianjung** [comment]
Thanks for your quick answer!

I actually tried both of the modifiers but none of them seem to work/help :/

Thanks anyway!

**Comment by jsnanigans** [comment]
I usually use margin or relative positioning to compensate
