### ISSUE TITLE
Please add an example

### ISSUE THREAD

**Issue by Lavhe** [jsnanigans/vue-parallax-js#13]
I see on the read me you only have a `<h1></h1>` it would be cool if you can add more html code maybe even including a background picture

**Comment by jsnanigans** [comment]
Hi there, this plugin does not do background pictures - you could but it would be very bad practice, I would highly recommend this plugin for background images: https://github.com/apertureless/vue-parallax

this `vue-parallax-js` is really only for elements.

I would gladly add some more examples if that would be helpful, could you maybe share with me how/for what you are using this plugin?
