### ISSUE TITLE
Bug: type error on window resize 

### ISSUE THREAD

**Issue by 40818419** [jsnanigans/vue-parallax-js#17]
<img width="459" alt="bildschirmfoto 2018-07-12 um 21 01 00" src="https://user-images.githubusercontent.com/2235499/42653824-e0ac367e-8616-11e8-9766-e95ef0960c7c.png">

**Comment by alijaya** [comment]
I think it's caused by offsetParent being null
[See here](https://stackoverflow.com/questions/306305/what-would-make-offsetparent-null)

I think it would be better if the code handles when offsetParent is null

**Comment by jsnanigans** [comment]
it could be that @alijaya but it could also be that the element is removed (maybe with a v-if) but the plugin still tries to animate it but the node does not exists anymore.

@40818419 are you using a v-if in your code?

**Comment by 40818419** [comment]
i'll investigate, but here is how i use it: https://github.com/sourcestream/sourcestream.de/blob/master/src/app/contentful/Hero/Hero.vue
