### ISSUE TITLE
On minWidth option, paralaxed element is not shown at all

### ISSUE THREAD

**Issue by 40818419** [jsnanigans/vue-parallax-js#18]
not sure if this is by design...

**Comment by jsnanigans** [comment]
Thanks for reporting this, on this line: https://github.com/jsnanigans/vue-parallax-js/blob/master/src/vue-parallax-js.js#L62 you can see that the style attribute is cleared when when minWidth is applied, this should not hide the element.
could you maybe show an example where this bug occurs?
