### ISSUE TITLE
Why offset is creating?

### ISSUE THREAD

**Issue by kodekrendel** [jsnanigans/vue-parallax-js#2]
How to not offset element when apply Parallax?

I have `<h2 v-parallax="0.8">One Morning<h2>`
When I load the page, this element are not on his place. Parallax is working, but why it's offsetting?

**Comment by kodekrendel** [comment]
In devTools I see that it applies `transform: translateY(-130.4px);` from the start when I load page. I don't thinks it's a correct behavior.

**Comment by kodekrendel** [comment]
As you can see, `transform: translateY(30px);` applied on page load, I don't use scroll.
![errooor](https://cloud.githubusercontent.com/assets/26049747/25045544/e59a2056-20fa-11e7-95bb-dd2edf2e9d6b.png)

**Comment by jsnanigans** [comment]
the absY modifyer should do the trick.
```
v-parallax.absY="0.2"
```

**Comment by kodekrendel** [comment]
@jsnanigans nope, I tried that. Still offset :cry:

**Comment by jsnanigans** [comment]
Damn, sorry...  
I have quite a big update coming soon, I think that will fix it. 
ill probably release it on monday

**Comment by kodekrendel** [comment]
@jsnanigans I appreciate it, that's probably the only right made parallax package for Vue on npm. I tried probably all of them with Nuxt already :smile: 
Looking forward for update, and thank you for assistance.

**Comment by timrijkse** [comment]
Would be cool to have a start and end scrollPos to avoid this behaviour :)

**Comment by jsnanigans** [comment]
thanks @kodekrendel :100: 
im glad that this is useful to someone else besides me.

i just release the update in the new beta branch, you should be able to install it with npm or yarn with `vue-parallax-js@0.1.0`

@timrijkse good idea ill keed that in mind the next time i have time to add features

**Comment by kodekrendel** [comment]
@jsnanigans this is helps! Thanks, great work. I see now it's transform3d, which is even more interesting :+1:
