### ISSUE TITLE
Browserify Issue

### ISSUE THREAD

**Issue by mmmarquez** [jsnanigans/vue-parallax-js#3]
Hello!

Excellent plugin! This might be an issue with my development workflow -- but might be worth mentioning. 

`/Users/mmarquez/.../parallax-test/node_modules/vue-parallax-js/vue-parallax-js.js:77
export default {
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

I can't seem to be able to run this directive using Browserify + Vue CLI Templates. By the console log it seems to be an issue with the babel.config, but I  can't seem to be able to get it to work. 

Everything works fine using Nuxt.js, which is Webpack based for compilation.

Any help would be appreciated -- most of my production sites are developed using Browserify and would like to implement this simple directive in some!

Thanks!

**Comment by jsnanigans** [comment]
hi, thanks for raising this bug, I never used browserify and didn't know that `export default` was nuxt specific. I just released version 0.0.5 where i changed it to `module.exports` which should fix that error.

Please try it and let me know if it works.

**Comment by mmmarquez** [comment]
hi!

Thanks for this fix -- I successfully implemented this project in my Browserify environment after your updated :) !
