### ISSUE TITLE
Perf In view port

### ISSUE THREAD

**Issue by ArrowBaZ** [jsnanigans/vue-parallax-js#6]
Hello,

Is it possible to add a in view port check to improve performance ?

like in this project:
https://github.com/erikengervall/parallax-vanilla/blob/master/src/js/translate.js

Would you some help to archive this ?

**Comment by jsnanigans** [comment]
Hi Beemo :),

I tried to implement this but found that it is really hard to figure out if the element is in the view port if you are animating the element itself, 
In erikengervall`s parallax-vanilla only the "background" of a element is animated and so its relatively easy to check if the element is in view or not.

Imagine a element that is positioned 200px below the viewport at load, if you scroll that element moves  equally as fast in the opposite direction that you scroll.
so if you scrolled down 100px, the element is now exactly on the bottom of the viewport and will show if you scroll any further.
If you would only be animating the element when it is already in the viewport this example element would only start moving up when you scrolled 200px.

I don't think that I will try to implement anything like this in this version, but I consider doing something like this, as far as possible, in the rewrite I am working on at the moment

**Comment by ArrowBaZ** [comment]
Hi !

Hum you are right, my use case was this one: https://www.nespresso.com/th/en/test-view2?s=test-hq-ol
it's very specifies since it's only background and not ui  element moving.

Thank for your plugin, we try many of parallax plugin and chose your !

**Comment by jsnanigans** [comment]
Im glad you like it :)
